### ISSUE TITLE
Lambda executions are not ordered by execution time

### ISSUE THREAD

**Issue by davidraviv** [Shuki-L/my-cli-tool#10]
**Describe the bug**

When listing "Lambda logs" and selecting the lambda, we get a list of all stream execution. The list is not ordered by time:

? Select log stream Lambda logs
? Select log group asset-service-local-monitor-delete-asset
? Select log stream
  1) 1) 2022-04-17 07:10:55
  2) 2) 2022-04-17 07:26:02
  3) 3) 2022-04-17 06:50:47
  4) 4) 2022-04-17 07:25:02

**To Reproduce**
1. Select: 1) Query localstack
2. Select: 1) Get Lambda logs
3. Select a lambda that has more than 3 executions
4. The stream log is not sorted by time.

**Expected behavior**
In the sample above, I would expect the streams to be sorted:
  2) 2) 2022-04-17 07:26:02
  4) 4) 2022-04-17 07:25:02
  1) 1) 2022-04-17 07:10:55
  3) 3) 2022-04-17 06:50:47

**Screenshots**
![Screen Shot 2022-04-17 at 10 32 43](https://user-images.githubusercontent.com/3273705/163705196-209b3dbc-e02a-494c-8d83-266387d13af9.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: Brave (but it is not relevant...)
 - Version: (Release: 0.0.5)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Shuki-L** [comment]
Thank you for reporting this bug @davidraviv 
Fixed on version [0.0.6](https://github.com/Shuki-L/my-cli-tool/releases/tag/0.0.6)
